id: P5779F7CB
initial_creation_type: input
source_metadata:
  title: Copper-Coloured Mountain
  language: pt
  description: 'Texts related to the Copper-Coloured Mountain of Glory (zangs mdog
    dpal ri), the heaven of Guru Padmasambhava:'
  volume:
    9281fbf7e4a54ef59033caf8bf9edffb:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Aspiration Prayers
    21a612855cf14807b0d6dde99b43c28b:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Aspiration Prayers
    026b4bd1e9fd426d9dcaee209816601a:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Aspiration Prayers
    dffbec22314045deab6941a08e0a3abb:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Aspiration Prayers
    c4ccdf1f826e4e0f839622ff3c6c2487:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Aspiration Prayers
    f83d991d85a34e45b771792af2f71c33:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Aspiration Prayers
    6ababd282a7145da82b5bede104e7026:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Aspiration Prayers
created_at: '2022-03-01T03:20:07.633930'
last_modified_at: '2022-03-01T03:20:07.633932'
